# Local properties for Payment Service
server:
  port: 8081

# Eureka Client Configuration
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Testing123$
    timeBetweenEvictionRunsMillis: 60000
    maxIdle: 1
    driver-class-name: com.mysql.cj.jdbc.Driver

# Below properties will automatically create and update database schema
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

# Sleuth configuration 100% of traces
management:
  tracing:
    sampling:
      probability: 1.0
